version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
        SBT_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - lighthouse-{{ checksum "project/Dependencies.scala" }}
      - run:
          name: Compile and run tests
          command: sbt test
      - run:
          name: Saving test results
          command: |
            mkdir ~/junit/
            find . -type f -regex ".*/target/test-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results: # Make test results visible in the UI
          path: ~/junit
      - store_artifacts: # Make test results downloadable as an artifact
          path: ~/junit
      - save_cache:
          key: lighthouse-{{ checksum "project/Dependencies.scala" }}-{{ checksum "build.sbt" }}
          paths:
            - ~/.sbt
            - ~/.coursier
            - ~/.ivy2